// Copyright (c) 2026, Arm Limited and contributors.
// SPDX-License-Identifier: Apache-2.0
//
// S32Z2 board bring-up: RTD init, UART9 console, newlib _write retarget.

#include <stdint.h>
#include <unistd.h>
#include <errno.h>

#include "platform/freertos/s32z2/board_init.h"

#include "Clock_Ip.h"
#include "Siul2_Port_Ip.h"
#include "Linflexd_Uart_Ip.h"
#include "Linflexd_Uart_Ip_VS_0_PBcfg.h"

// S32CT-generated pin-mux table. NUM_OF_CONFIGURED_PINS comes from the board
// Siul2_Port_Ip_Cfg.h; g_pin_mux_InitConfigArr_VS_0 (the actual pad settings)
// from the generated PB cfg. This table muxes the NETC ETH0 RGMII pins
// (SIUL2_1[58..65] -> ALT1 = ETH_0_RGMII_TXD/RXD/TXC/TXCTL/RXCTL/RX_CLK) plus
// the PHY GPIO control pins. The lwip example applies it via Port_Init(); we
// apply it directly with Siul2_Port_Ip_Init() (see board_init()).
#include "Siul2_Port_Ip_Cfg.h"
#include "Siul2_Port_Ip_VS_0_PBcfg.h"

// AUTOSAR Mcu_Init / Port_Init / Platform_Init would require Mcu_Cfg.c /
// Port_Cfg.c / Platform_Cfg.c — those PB configs are absent from the lwip
// S32CT example (Components view does not instantiate them), so the build
// filters them out. The NXP startup.s + SystemInit handle MCU bring-up
// before main(); we still need the IP-layer Clock_Ip_Init below to enable
// the LINFLEXD9 module clock that SystemInit does not touch.

// Mcu_aClockConfigPB[] is defined in Clock_Ip_VS_0_PBcfg.c (S32CT
// generated). The lwip example uses the AUTOSAR-Mcu naming
// (Mcu_aClockConfigPB) rather than the bare Clock_Ip_aClockConfig from
// non-AUTOSAR examples — both are the same Clock_Ip_ClockConfigType
// array. Element 0 is the default ClockConfig0 that turns the LINFLEXD9
// module clock on.
extern const Clock_Ip_ClockConfigType Mcu_aClockConfigPB[];

// LINFLEXD instance 9 is wired to the X-S32Z27X-DC FT232RQ console
// (matches the Zephyr `_D` overlay's `zephyr,console = &uart9`).
// PB cfg symbol is generated by S32CT into Linflexd_Uart_Ip_VS_0_PBcfg.c.
extern const Linflexd_Uart_Ip_UserConfigType Linflexd_Uart_Ip_xHwConfigPB_0_VS_0;

// SIUL2_5 PORT150 → ALT1 → LIN_9_TX. The S32CT Pins tool added the routing
// to the .mex but the Update Code action did not regenerate the Siul2_Port
// PB cfg, so we configure the pad inline via the RTD IP-layer API.
static const Siul2_Port_Ip_PinSettingsConfig kLin9TxPin = {
    .base                     = IP_SIUL2_5,
    .pinPortIdx               = 150U,
    .mux                      = PORT_MUX_ALT1,
    .safeMode                 = PORT_SAFE_MODE_DISABLED,
    .pullConfig               = PORT_INTERNAL_PULL_NOT_ENABLED,
    .slewRateCtrlSel          = PORT_SLEW_RATE_CONTROL0,
    .receiverSel              = PORT_RECEIVER_NOT_AVAILABLE,
    .terminationResistor      = PORT_TERMINATION_RESISTOR_NOT_AVAILABLE,
    .currentReferenceControl  = PORT_CURRENT_REFERENCE_CONTROL_NOT_AVAILABLE,
    .rxCurrentBoost           = PORT_RX_CURRENT_BOOST_NOT_AVAILABLE,
    .openDrain                = PORT_OPEN_DRAIN_DISABLED,
    .inputBuffer              = PORT_INPUT_BUFFER_DISABLED,
    .outputBuffer             = PORT_OUTPUT_BUFFER_ENABLED,
    .initValue                = 0U,
    .inputMuxReg              = { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U },
    .inputMux                 = { 0U, 0U, 0U, 0U, 0U, 0U, 0U, 0U },
};

void uart9_init_115200_8N1(void) {
    Siul2_Port_Ip_PinInit(&kLin9TxPin);
    (void)Linflexd_Uart_Ip_Init(9U, &Linflexd_Uart_Ip_xHwConfigPB_0_VS_0);
}

int uart9_tx_byte(uint8_t b) {
    return (Linflexd_Uart_Ip_SyncSend(9U, &b, 1U, 100U)
            == LINFLEXD_UART_IP_STATUS_SUCCESS) ? 0 : -1;
}

// The S32CT clock config (Clock_Ip_VS_0_PBcfg.c) sets up COREPLL and the
// P0/P1/P2 partition system clocks but contains NO selector for RTU0_CORE_CLK,
// so Clock_Ip_Init() never programs the RTU0 core CGM mux
// (IP_RTU0__MC_CGM->MUX_0, CGM7 @ 0x762C0000) and the R52 we run on stays at its
// reset default source SELCTL=0 = FIRC = 48 MHz. Confirmed at runtime:
// Clock_Ip_GetClockFrequency(RTU0_CORE_CLK) == 48 MHz and MUX_0 CSC == 0. That
// uniform ~16x under-clock — not caches or SIMD — dominated the MPC cycle.
// COREPLL is already locked by Clock_Ip_Init and COREPLL_DFS0 reads exactly
// 800 MHz (global CGM selector source index 11). Clock_Ip_Init also already
// provisioned the RTU0 SRAM wait states for 800 MHz (Clock_Ip_Specific.c reads
// the RTU0_CORE_CLK=800 MHz ConfiguredFrequencies entry to set RAM IWS), so
// raising the core clock is safe. Perform the glitchless CGM switch here,
// mirroring the proven ETH0 RX-clock mux sequence in lwip_bringup.c.
#define RTU0_MC_CGM_MUX_0_CSC   0x762C0300UL
#define RTU0_MC_CGM_MUX_0_CSS   0x762C0304UL
#define RTU0_MC_CGM_MUX_0_DC_0  0x762C0308UL
#define RTU0_CORE_SRC_COREPLL_DFS0  11U   /* CGM selector source index = 800 MHz */
#define RTU0_CGM_REG32(a)  (*(volatile uint32_t *)(a))

static void rtu0_core_clock_to_800mhz(void) {
    /* Already sourced from COREPLL_DFS0 (e.g. boot-over-running)? Nothing to do. */
    if (((RTU0_CGM_REG32(RTU0_MC_CGM_MUX_0_CSS) >> 24) & 0x3FU)
            == RTU0_CORE_SRC_COREPLL_DFS0) {
        return;
    }
    for (int attempt = 0; attempt < 4; ++attempt) {
        /* SELCTL = COREPLL_DFS0, CLK_SW = 1 (request the glitchless switch). */
        RTU0_CGM_REG32(RTU0_MC_CGM_MUX_0_CSC) =
            (RTU0_CORE_SRC_COREPLL_DFS0 << 24) | (1U << 2);
        /* Poll switch-in-progress (CSS bit16, SWIP) until it clears. */
        for (int t = 0; t < 200000; ++t) {
            if ((RTU0_CGM_REG32(RTU0_MC_CGM_MUX_0_CSS) & 0x10000U) == 0U) {
                break;
            }
        }
        /* Done once SELSTAT == requested SELCTL. */
        if (((RTU0_CGM_REG32(RTU0_MC_CGM_MUX_0_CSS) >> 24) & 0x3FU)
                == RTU0_CORE_SRC_COREPLL_DFS0) {
            break;
        }
    }
    /* Keep the divider at /1 (DE=1, DIV=0): 800 MHz / 1 = 800 MHz. */
    RTU0_CGM_REG32(RTU0_MC_CGM_MUX_0_DC_0) = 0x80000000U;
}

int board_init(void) {
    (void)Clock_Ip_Init(&Mcu_aClockConfigPB[0U]);
    rtu0_core_clock_to_800mhz();
    uart9_init_115200_8N1();
    // Mux the NETC ETH0 RGMII + PHY-control pins. Without this the MAC<->PHY
    // RGMII pins stay at their reset function and the Ethernet wire interface is
    // dead in BOTH directions (no TX on the wire, no RX) -- the lwip example
    // does this inside Port_Init(), which the board otherwise skips.
    (void)Siul2_Port_Ip_Init(NUM_OF_CONFIGURED_PINS, g_pin_mux_InitConfigArr_VS_0);
    return 0;
}

// generic_timer.c registers SysTick_Handler as the physical-timer ISR but
// leaves it up to the application. We alias it to the CR52 port's
// xPortSysTickHandler via a linker --defsym in CMakeLists.txt.

// Newlib retarget: every printf/puts/fwrite to stdout/stderr ends up here.
int _write(int fd, const char *buf, int len) {
    if (fd != 1 && fd != 2) {
        errno = EBADF;
        return -1;
    }
    for (int i = 0; i < len; ++i) {
        if (uart9_tx_byte((uint8_t)buf[i]) != 0) {
            return i;
        }
    }
    return len;
}

// Newlib stubs to keep the link clean for bare metal.
int _close(int fd) { (void)fd; errno = EBADF; return -1; }
int _lseek(int fd, int off, int whence) { (void)fd; (void)off; (void)whence; errno = EBADF; return -1; }
int _read(int fd, char *buf, int len) { (void)fd; (void)buf; (void)len; errno = EBADF; return -1; }
int _fstat(int fd, void *st) { (void)fd; (void)st; errno = EBADF; return -1; }
int _isatty(int fd) { return (fd == 1 || fd == 2) ? 1 : 0; }
int _getpid(void) { return 1; }
int _kill(int pid, int sig) { (void)pid; (void)sig; errno = EINVAL; return -1; }

// The FreeRTOS tick is driven by the Cortex-R52 generic timer (NXP
// generic_timer.c), whose SysTick_Handler is aliased to the port's
// xPortSysTickHandler via a linker --defsym in CMakeLists.txt. The previous
// PIT-backed tick (Pit_Ip_* placeholder stubs wired through
// configSETUP_TICK_INTERRUPT) was an unused second tick source and was removed.
