# Copyright (c) 2026, Arm Limited.
# SPDX-License-Identifier: Apache-2.0

# DDS-over-TAP network configuration for FVP. The host side should assign tap0
# 192.168.10.1/24 and run CycloneDDS Domain 2 on that interface.
CONFIG_NET_DHCPV4=n
CONFIG_NET_IFACE1_ADDR="192.168.10.2"
CONFIG_NET_IFACE1_GW="192.168.10.1"
CONFIG_NET_IFACE1_NETMASK="255.255.255.0"
