set(ament_cmake_auto_FOUND TRUE)
# Provide ament_auto_* macros as thin wrappers.
function(ament_auto_find_build_dependencies)        endfunction()
function(ament_auto_add_library target)
  set(srcs "")
  foreach(arg IN LISTS ARGN)
    if(NOT arg STREQUAL "SHARED" AND NOT arg STREQUAL "STATIC")
      list(APPEND srcs "${arg}")
    endif()
  endforeach()
  add_library(${target} STATIC ${srcs})
endfunction()
function(ament_auto_add_executable target)
  add_executable(${target} ${ARGN})
endfunction()
function(ament_auto_package)                        endfunction()
function(ament_auto_add_gtest)                      endfunction()
